services:
  app:
    build:
      context: ./
      dockerfile: DockerFile
    command: >
      sh -c "cd /app &&
             pip install --root-user-action=ignore --upgrade pip &&
             pip install --root-user-action=ignore -r requirements.txt &&
             flask run --host=0.0.0.0 --port=5000"
    ports:
      - 5000:5000
    env_file:
      - ./.env