apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  STORES_LIST_URL: https://feeds.brightoncollectibles.com/get?feed=bristore

---
apiVersion: v1
kind: Service
metadata:
  name: brighton-service
spec:
  selector:
    app: brighton-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brighton-app
spec:
  selector:
    matchLabels:
      app: brighton-app
  replicas: 3
  template:
    metadata:
      labels:
        app: brighton-app
    spec:
      containers:
        - name: brighton-app
          image: docker.io/shaktishri/brighton-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
              name: app-config

